_templates:
  - &rake
    command: "bin/rake"
    plugins:
      docker-compose#v3.3.0:
        run: app
        config: .buildkite/docker-compose.yml
    timeout_in_minutes: 10

steps:
  - <<: *rake
    name: ":ruby: 2.5"
    env:
      RUBY_IMAGE: "ruby:2.5"
  - <<: *rake
    name: ":ruby: 2.6"
    env:
      RUBY_IMAGE: "ruby:2.6"
  - <<: *rake
    name: ":ruby: 2.7"
    env:
      RUBY_IMAGE: "ruby:2.7"
  - <<: *rake
    name: ":ruby: 3.0"
    env:
      RUBY_IMAGE: "ruby:3.0"
  - <<: *rake
    name: ":ruby: 3.1"
    env:
      RUBY_IMAGE: "ruby:3.1"
  - <<: *rake
    name: ":ruby: 3.2"
    env:
      RUBY_IMAGE: "ruby:3.2"
  - <<: *rake
    name: ":ruby: 3.3"
    env:
      RUBY_IMAGE: "ruby:3.3"
  - <<: *rake
    name: ":ruby: 3.4"
    env:
      RUBY_IMAGE: "ruby:3.4"
  - <<: *rake
    name: ":ruby: nightly"
    env:
      RUBY_IMAGE: "rubylang/ruby:master-nightly-focal"
  - <<: *rake
    name: "JRuby"
    env:
      RUBY_IMAGE: "jruby"
    soft_fail: true
