#!/usr/bin/env ruby
# frozen_string_literal: true

if defined?(::Gem) && !defined?(::Gel)
  # Note there's a similar re-exec in gemlib/gel/stub.rb

  exec ::Gem.ruby,
    "-I", File.expand_path("../slib", __dir__),
    "--",
    __FILE__,
    *ARGV
end

require_relative "../lib/gel/command"
Gel::Command.run(ARGV)
